"use client";

import { useEffect, useMemo, useState } from "react";

type HistogramBin = { start: number; end: number; count: number };
type Term = { term: string; count?: number; weight?: number };
type ProductRecord = { id: string; name: string; category: string; topCategory: string; actualPrice: number | null; discountedPrice: number | null; rating: number | null; ratingCount: number | null; discountPercentage: number | null };
type DashboardData = {
  dataset: { sourceRows: number; cleanRows: number; uniqueProducts: number; uniqueCategories: number; topLevelCategories: number; generatedAt: string };
  quality: { exactDuplicateRowsRemoved: number; missingByField: Record<string, number>; cleaningRules: string[] };
  reviewIntelligence: { reviewRecords: number; averageReviewWords: number; positiveTerms: Term[]; negativeTerms: Term[]; method: string };
  productRecords: ProductRecord[];
};
type ModelMetric = { name: string; type: string; accuracy: number; precision: number; recall: number; f1: number; rocAuc: number | null };
type ModelPayload = {
  evaluation: { status: string; threshold: number; thresholdNote: string; classDistribution: { label: string; count: number }[]; split: { train: number; test: number; randomState: number; stratified: boolean }; models: ModelMetric[]; bestModel: string; confusionMatrix: { truePositive: number; falseNegative: number; falsePositive: number; trueNegative: number; labelOrder: string }; explainability: { model: string; note: string; positiveTerms: Term[]; negativeTerms: Term[] } };
  inference: { modelName: string; threshold: number; intercept: number; vocabulary: Record<string, number>; idf: number[]; coefficients: number[]; tokenPattern: string; note: string };
};
type Prediction = { probability: number; matches: { term: string; contribution: number }[] } | { error: string };
type Range = { label: string; min?: number; max?: number };

const ratingRanges: Record<string, Range> = { all: { label: "All ratings" }, under4: { label: "Below 4.0", max: 4 }, fourTo42: { label: "4.0 to <4.2", min: 4, max: 4.2 }, high: { label: "4.2 and above", min: 4.2 } };
const discountRanges: Record<string, Range> = { all: { label: "All discounts" }, noTo25: { label: "0–25%", min: 0, max: 25 }, twentyFiveTo50: { label: "25–50%", min: 25, max: 50 }, fiftyPlus: { label: "50% and above", min: 50 } };
const priceRanges: Record<string, Range> = { all: { label: "All discounted prices" }, under500: { label: "Up to ₹500", max: 500 }, fiveTo15: { label: "₹500–₹1,500", min: 500, max: 1500 }, fifteenTo30: { label: "₹1,500–₹3,000", min: 1500, max: 3000 }, over30: { label: "Above ₹3,000", min: 3000 } };
const stopWords = new Set("a about above after again against all am an and any are as at be because been before being below between both but by can could did do does doing down during each few for from further had has have having he her here hers herself him himself his how i if in into is it its itself just me more most my myself no nor not now of off on once only or other our ours ourselves out over own same she should so some such than that the their theirs them themselves then there these they this those through to too under until up very was we were what when where which while who whom why will with would you your yours yourself yourselves".split(" "));
const compact = new Intl.NumberFormat("en-IN", { notation: "compact", maximumFractionDigits: 1 });
const decimals = new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 });
const number = (value: number | null | undefined) => value === null || value === undefined || Number.isNaN(value) ? "—" : decimals.format(value);
const percent = (value: number | null | undefined) => value === null || value === undefined ? "—" : `${(value * 100).toFixed(1)}%`;
const shortCategory = (value: string) => value.split("|").at(-1)?.trim() || value;
const inRange = (value: number | null, range: Range) => value !== null && value !== undefined && (range.min === undefined || value >= range.min) && (range.max === undefined || value < range.max);

function buildHistogram(values: Array<number | null>, minimum: number, maximum: number) {
  const bins = Array.from({ length: 10 }, (_, index) => ({ start: minimum + ((maximum - minimum) / 10) * index, end: minimum + ((maximum - minimum) / 10) * (index + 1), count: 0 }));
  for (const value of values) if (value !== null && value !== undefined && value >= minimum && value <= maximum) bins[Math.min(Math.floor(((value - minimum) / Math.max(maximum - minimum, 1)) * 10), 9)].count += 1;
  return bins;
}

function correlation(rows: ProductRecord[], x: (row: ProductRecord) => number | null, y: (row: ProductRecord) => number | null) {
  const pairs = rows.map((row) => [x(row), y(row)] as const).filter((pair): pair is [number, number] => pair[0] !== null && pair[1] !== null);
  if (pairs.length < 2) return null;
  const xMean = pairs.reduce((sum, pair) => sum + pair[0], 0) / pairs.length; const yMean = pairs.reduce((sum, pair) => sum + pair[1], 0) / pairs.length;
  const numerator = pairs.reduce((sum, pair) => sum + (pair[0] - xMean) * (pair[1] - yMean), 0);
  const denominator = Math.sqrt(pairs.reduce((sum, pair) => sum + (pair[0] - xMean) ** 2, 0) * pairs.reduce((sum, pair) => sum + (pair[1] - yMean) ** 2, 0));
  return denominator ? numerator / denominator : null;
}

function Histogram({ bins, label, suffix = "" }: { bins: HistogramBin[]; label: string; suffix?: string }) {
  const max = Math.max(...bins.map((bin) => bin.count), 1);
  return <div className="amazon-histogram" role="img" aria-label={label}>{bins.map((bin) => <div className="amazon-hist-bin" key={`${bin.start}-${bin.end}`}><div className="amazon-hist-track"><span style={{ height: `${Math.max((bin.count / max) * 100, 2)}%` }}><i>{bin.count}</i></span></div><small>{`${bin.start.toFixed(suffix ? 0 : 1)}${suffix}`}</small></div>)}</div>;
}

function ScatterPlot({ rows, label, xLabel, yLabel, getX, getY, xLog = false }: { rows: ProductRecord[]; label: string; xLabel: string; yLabel: string; getX: (row: ProductRecord) => number | null; getY: (row: ProductRecord) => number | null; xLog?: boolean }) {
  const points = rows.map((row) => ({ row, x: getX(row), y: getY(row) })).filter((point): point is { row: ProductRecord; x: number; y: number } => point.x !== null && point.y !== null).slice(0, 400);
  if (!points.length) return <p className="playground-note">No complete numeric pairs are available for the selected filters.</p>;
  const convertedX = points.map((point) => xLog ? Math.log10(point.x + 1) : point.x); const valuesY = points.map((point) => point.y);
  const minX = Math.min(...convertedX, 0); const maxX = Math.max(...convertedX, 1); const minY = Math.min(...valuesY, 0); const maxY = Math.max(...valuesY, 1);
  const scaled = (value: number, min: number, max: number, start: number, size: number) => start + ((value - min) / Math.max(max - min, 1)) * size;
  return <><svg className="amazon-scatter" viewBox="0 0 440 235" role="img" aria-label={label}><path d="M42 190H416M42 126H416M42 62H416M42 30V190" />{points.map((point, index) => { const x = scaled(xLog ? Math.log10(point.x + 1) : point.x, minX, maxX, 42, 374); const y = 190 - scaled(point.y, minY, maxY, 0, 160); return <circle key={`${point.row.id}-${index}`} cx={x} cy={y} r="2.7"><title>{`${point.row.name} — ${xLabel}: ${number(point.x)}; ${yLabel}: ${number(point.y)}`}</title></circle>; })}</svg><div className="chart-axis"><span>{xLabel}</span><span>{yLabel}</span><span>{`${points.length} points shown`}</span></div></>;
}

function TermList({ title, terms, tone }: { title: string; terms: Term[]; tone: "positive" | "negative" }) {
  const max = Math.max(...terms.map((term) => Math.abs(term.count ?? term.weight ?? 0)), 1);
  return <div className={`amazon-term-list amazon-term-list-${tone}`}><p className="mono">{title}</p>{terms.map((term) => { const value = Math.abs(term.count ?? term.weight ?? 0); return <div key={term.term}><span>{term.term}</span><i style={{ width: `${Math.max((value / max) * 100, 3)}%` }} /><b>{term.count ?? number(term.weight)}</b></div>; })}</div>;
}

function runInference(text: string, model: ModelPayload["inference"]): Prediction {
  const tokens = (text.toLowerCase().match(/[a-z]{2,}/g) ?? []).filter((token) => !stopWords.has(token));
  if (!tokens.length) return { error: "Enter a short English product or review description to test the exported model vocabulary." };
  const features = [...tokens, ...tokens.slice(0, -1).map((token, index) => `${token} ${tokens[index + 1]}`)];
  const counts = new Map<number, { term: string; count: number }>();
  for (const feature of features) { const index = model.vocabulary[feature]; if (index !== undefined) { const current = counts.get(index); counts.set(index, { term: feature, count: (current?.count ?? 0) + 1 }); } }
  if (!counts.size) return { error: "No terms from this input appear in the exported TF-IDF vocabulary. Try more specific product or review language." };
  const weighted = [...counts.entries()].map(([index, entry]) => ({ index, term: entry.term, weight: entry.count * model.idf[index] })); const norm = Math.sqrt(weighted.reduce((sum, item) => sum + item.weight ** 2, 0)) || 1;
  const contributions = weighted.map((item) => ({ term: item.term, contribution: (item.weight / norm) * model.coefficients[item.index] })); const score = model.intercept + contributions.reduce((sum, item) => sum + item.contribution, 0);
  return { probability: 1 / (1 + Math.exp(-score)), matches: contributions.sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution)).slice(0, 8) };
}

export function AmazonDashboard() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [model, setModel] = useState<ModelPayload | null>(null); const [error, setError] = useState("");
  const [category, setCategory] = useState("All categories"); const [ratingRange, setRatingRange] = useState("all"); const [discountRange, setDiscountRange] = useState("all"); const [priceRange, setPriceRange] = useState("all"); const [query, setQuery] = useState(""); const [filtersOpen, setFiltersOpen] = useState(true); const [predictionInput, setPredictionInput] = useState(""); const [prediction, setPrediction] = useState<Prediction | null>(null);

  useEffect(() => { let live = true; if (window.matchMedia("(max-width: 720px)").matches) setFiltersOpen(false); Promise.all([fetch("/data/amazon/amazon-dashboard.json"), fetch("/data/amazon/amazon-model.json")]).then(async ([dashboardResponse, modelResponse]) => { if (!dashboardResponse.ok || !modelResponse.ok) throw new Error("The local data artifact could not be loaded."); return [await dashboardResponse.json(), await modelResponse.json()] as [DashboardData, ModelPayload]; }).then(([dashboardData, modelData]) => { if (live) { setDashboard(dashboardData); setModel(modelData); } }).catch(() => { if (live) setError("The local Amazon data artifacts are unavailable. Rebuild public/data/amazon/ from analysis/amazon/analyze_amazon.py and export the static site again."); }); return () => { live = false; }; }, []);

  const categories = useMemo(() => dashboard ? ["All categories", ...Array.from(new Set(dashboard.productRecords.map((item) => item.category))).sort()] : [], [dashboard]);
  const filtered = useMemo(() => dashboard?.productRecords.filter((item) => (category === "All categories" || item.category === category) && inRange(item.rating, ratingRanges[ratingRange]) && (discountRange === "all" || inRange(item.discountPercentage, discountRanges[discountRange])) && (priceRange === "all" || inRange(item.discountedPrice, priceRanges[priceRange]))) ?? [], [dashboard, category, ratingRange, discountRange, priceRange]);
  const tableRows = useMemo(() => filtered.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())).slice(0, 12), [filtered, query]);
  const ratingHistogram = useMemo(() => buildHistogram(filtered.map((item) => item.rating), 0, 5), [filtered]); const discountHistogram = useMemo(() => buildHistogram(filtered.map((item) => item.discountPercentage), 0, 100), [filtered]);
  const categoryBars = useMemo(() => { const counts = new Map<string, number>(); filtered.forEach((item) => counts.set(item.category, (counts.get(item.category) ?? 0) + 1)); return [...counts.entries()].map(([name, records]) => ({ category: name, records, percent: filtered.length ? (records / filtered.length) * 100 : 0 })).sort((a, b) => b.records - a.records).slice(0, 10); }, [filtered]);
  const activeProducts = new Set(filtered.map((item) => item.id)).size; const avgRating = filtered.length ? filtered.reduce((sum, item) => sum + (item.rating ?? 0), 0) / filtered.filter((item) => item.rating !== null).length : null; const availableDiscounts = filtered.filter((item) => item.discountPercentage !== null); const avgDiscount = availableDiscounts.length ? availableDiscounts.reduce((sum, item) => sum + (item.discountPercentage ?? 0), 0) / availableDiscounts.length : null;
  const activeCategory = category === "All categories" ? null : category; const selectedCategoryRows = activeCategory ? filtered : []; const medianPrice = selectedCategoryRows.length ? [...selectedCategoryRows].map((item) => item.discountedPrice).filter((value): value is number => value !== null).sort((a, b) => a - b)[Math.floor(selectedCategoryRows.filter((item) => item.discountedPrice !== null).length / 2)] ?? null : null;
  const resetFilters = () => { setCategory("All categories"); setRatingRange("all"); setDiscountRange("all"); setPriceRange("all"); setQuery(""); };

  if (error) return <div className="amazon-dashboard-state empty-state" role="status"><p className="mono">Static data unavailable</p><p>{error}</p></div>;
  if (!dashboard || !model) return <div className="amazon-dashboard-state amazon-loading" role="status" aria-live="polite" aria-busy="true"><p className="mono">Loading local data artifacts</p><div /><div /><div /></div>;

  const { dataset, quality, reviewIntelligence } = dashboard; const { evaluation } = model;
  return <div className="amazon-dashboard" aria-label="Amazon Product Intelligence dashboard">
    <div className="amazon-dashboard-intro"><p className="mono">Static data lab / supplied Amazon CSV</p><p>Every value is calculated from local JSON generated by the accompanying Python analysis. Global filters update the product-derived KPIs and charts below; fixed review terms and held-out model metrics remain explicitly labeled as full-snapshot artifacts.</p></div>
    <div className="amazon-filter-rack"><button className="amazon-filter-toggle mono" type="button" aria-expanded={filtersOpen} aria-controls="amazon-global-filters" onClick={() => setFiltersOpen((value) => !value)}><span>Global filters</span><i>{filtersOpen ? "−" : "+"}</i></button>{filtersOpen && <div id="amazon-global-filters" className="amazon-filter-controls"><label><span className="mono">Category path</span><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Filter by Amazon category">{categories.map((item) => <option key={item} value={item}>{item === "All categories" ? item : shortCategory(item)}</option>)}</select></label><label><span className="mono">Rating</span><select value={ratingRange} onChange={(event) => setRatingRange(event.target.value)} aria-label="Filter by rating range">{Object.entries(ratingRanges).map(([key, range]) => <option key={key} value={key}>{range.label}</option>)}</select></label><label><span className="mono">Discount</span><select value={discountRange} onChange={(event) => setDiscountRange(event.target.value)} aria-label="Filter by discount range">{Object.entries(discountRanges).map(([key, range]) => <option key={key} value={key}>{range.label}</option>)}</select></label><label><span className="mono">Discounted price</span><select value={priceRange} onChange={(event) => setPriceRange(event.target.value)} aria-label="Filter by discounted price range">{Object.entries(priceRanges).map(([key, range]) => <option key={key} value={key}>{range.label}</option>)}</select></label><button className="reset-button mono" type="button" onClick={resetFilters}>Reset all</button></div>}</div>
    <div className="kpi-grid amazon-kpi-grid" aria-live="polite"><div><span className="mono">Active records</span><strong>{compact.format(filtered.length)}</strong><p>Of {dataset.sourceRows} source rows; the one missing rating is not in the filterable records.</p></div><div><span className="mono">Active products</span><strong>{compact.format(activeProducts)}</strong><p>Unique product IDs in the active view.</p></div><div><span className="mono">Average rating</span><strong>{number(avgRating)}</strong><p>Computed from the currently filtered records.</p></div><div><span className="mono">Average discount</span><strong>{number(avgDiscount)}%</strong><p>Computed where an observed discount is present.</p></div></div>
    {activeCategory && <div className="amazon-stat-strip" aria-live="polite"><span className="mono">Selected path</span><strong>{activeCategory}</strong><div><b>{filtered.length}</b><span>active records</span></div><div><b>{number(avgRating)}</b><span>avg. rating</span></div><div><b>{number(avgDiscount)}%</b><span>avg. discount</span></div><div><b>{medianPrice === null ? "—" : `₹${compact.format(medianPrice)}`}</b><span>median discounted price</span></div></div>}
    {!filtered.length && <div className="empty-state amazon-empty-state" role="status"><p className="mono">No records match these filters</p><button type="button" onClick={resetFilters}>Reset all filters</button></div>}
    <section className="amazon-section-grid" aria-labelledby="amazon-distribution-title"><div className="chart-panel"><div className="chart-heading"><p id="amazon-distribution-title" className="mono">Rating distribution</p><span>active view / 0–5</span></div><Histogram bins={ratingHistogram} label="Histogram of filtered Amazon product ratings" /><p className="playground-note">One rating is missing in the source and cannot be part of rating-based filters.</p></div><div className="chart-panel"><div className="chart-heading"><p className="mono">Discount distribution</p><span>active view / 0–100%</span></div><Histogram bins={discountHistogram} label="Histogram of filtered discount percentages" suffix="%" /><p className="playground-note">Price and discount strings are normalized in the reproducible pipeline.</p></div></section>
    <section className="amazon-section-grid" aria-labelledby="amazon-category-title"><div className="chart-panel"><div className="chart-heading"><p id="amazon-category-title" className="mono">Most frequent category paths</p><span>Top 10 / active view</span></div><div className="amazon-category-bars">{categoryBars.map((item) => <div key={item.category}><span title={item.category}>{shortCategory(item.category)}</span><i><b style={{ width: `${item.percent}%` }} /></i><em>{item.records}</em></div>)}</div>{!categoryBars.length && <p className="playground-note">No category paths are in the active view.</p>}<p className="playground-note">A category is a full pipe-delimited path, not a deduplicated product taxonomy.</p></div><div className="chart-panel"><div className="chart-heading"><p className="mono">Observed correlations</p><span>Pearson / active view</span></div><div className="amazon-correlation"><div><span className="mono">Rating × rating count</span><strong>{number(correlation(filtered, (row) => row.rating, (row) => row.ratingCount))}</strong></div><div><span className="mono">Discount × rating</span><strong>{number(correlation(filtered, (row) => row.discountPercentage, (row) => row.rating))}</strong></div></div><p className="playground-note">Correlation is descriptive. The snapshot contains no experiment or causal outcome data.</p></div></section>
    <section className="amazon-section-grid" aria-label="Scatter plots filtered by global Amazon controls"><div className="chart-panel"><div className="chart-heading"><p className="mono">Rating versus rating count</p><span>active view / log x</span></div><ScatterPlot rows={filtered} label="Scatter plot of filtered rating count and rating" xLabel="rating count (log scale)" yLabel="rating" getX={(row) => row.ratingCount} getY={(row) => row.rating} xLog /></div><div className="chart-panel"><div className="chart-heading"><p className="mono">Discount versus rating</p><span>active view / raw</span></div><ScatterPlot rows={filtered} label="Scatter plot of filtered discount percentage and rating" xLabel="discount %" yLabel="rating" getX={(row) => row.discountPercentage} getY={(row) => row.rating} /></div></section>
    <section className="amazon-product-explorer table-panel" aria-labelledby="amazon-product-title"><div className="table-heading"><p id="amazon-product-title" className="mono">Product explorer</p><label><span className="sr-only">Search current filtered Amazon products</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search active product names" aria-label="Search active product names" /></label></div><div className="table-scroll"><table aria-label="Amazon products matching the active filters"><thead><tr><th scope="col">Product</th><th scope="col">Path</th><th scope="col">Rating</th><th scope="col">Ratings</th><th scope="col">Discount</th></tr></thead><tbody>{tableRows.map((item) => <tr key={`${item.id}-${item.name}`}><td title={item.name}>{item.name}</td><td title={item.category}>{shortCategory(item.category)}</td><td>{number(item.rating)}</td><td>{item.ratingCount === null ? "—" : compact.format(item.ratingCount)}</td><td>{item.discountPercentage === null ? "—" : `${number(item.discountPercentage)}%`}</td></tr>)}</tbody></table>{!tableRows.length && <p className="playground-note">No product names match the current filters and local search.</p>}</div></section>
    <section className="amazon-review-section" aria-labelledby="amazon-review-title"><div className="amazon-section-heading"><p className="mono">Review intelligence / full snapshot</p><h3 id="amazon-review-title">Language signals, kept contextual.</h3><p>{reviewIntelligence.reviewRecords} records contain review text; the average non-empty review has {number(reviewIntelligence.averageReviewWords)} words.</p></div><div className="amazon-term-grid"><TermList title="Frequent terms / rating ≥ 4.2" terms={reviewIntelligence.positiveTerms} tone="positive" /><TermList title="Frequent terms / rating < 4.2" terms={reviewIntelligence.negativeTerms} tone="negative" /></div><p className="playground-note">{reviewIntelligence.method} These terms stay fixed because raw review text is not published into this dashboard artifact.</p></section>
    <section id="model" className="amazon-model-section" aria-labelledby="amazon-model-title"><div className="amazon-section-heading"><p className="mono">Held-out model evaluation / full snapshot</p><h3 id="amazon-model-title">A benchmark, not a product decision.</h3><p>{evaluation.thresholdNote} The split is {evaluation.split.train} training / {evaluation.split.test} test records, stratified with random state {evaluation.split.randomState}.</p></div><div className="table-panel"><div className="table-heading"><p className="mono">Model comparison</p><span className="mono">Best F1 / {evaluation.bestModel}</span></div><div className="table-scroll"><table aria-label="Model evaluation results on a held-out test set"><thead><tr><th scope="col">Model</th><th scope="col">Accuracy</th><th scope="col">Precision</th><th scope="col">Recall</th><th scope="col">F1</th><th scope="col">ROC-AUC</th></tr></thead><tbody>{evaluation.models.map((item) => <tr className={item.name === evaluation.bestModel ? "amazon-best-model" : ""} key={item.name}><td>{item.name}{item.name === evaluation.bestModel && <span className="mono"> best</span>}</td><td>{percent(item.accuracy)}</td><td>{percent(item.precision)}</td><td>{percent(item.recall)}</td><td>{percent(item.f1)}</td><td>{percent(item.rocAuc)}</td></tr>)}</tbody></table></div></div><div className="amazon-model-lower"><div className="chart-panel"><div className="chart-heading"><p className="mono">Best model confusion matrix</p><span>Actual / predicted</span></div><div className="amazon-confusion" role="img" aria-label="Confusion matrix for the best Linear SVM model"><span>actual ↓ / predicted →</span><span>High</span><span>Not high</span><span>High</span><strong>{evaluation.confusionMatrix.truePositive}<small>TP</small></strong><strong>{evaluation.confusionMatrix.falseNegative}<small>FN</small></strong><span>Not high</span><strong>{evaluation.confusionMatrix.falsePositive}<small>FP</small></strong><strong>{evaluation.confusionMatrix.trueNegative}<small>TN</small></strong></div></div><div className="chart-panel"><div className="chart-heading"><p className="mono">Coefficient evidence</p><span>{evaluation.explainability.model}</span></div><div className="amazon-term-grid compact"><TermList title="Toward high rating" terms={evaluation.explainability.positiveTerms} tone="positive" /><TermList title="Toward not-high rating" terms={evaluation.explainability.negativeTerms} tone="negative" /></div><p className="playground-note">{evaluation.explainability.note}</p></div></div></section>
    <section className="amazon-predict-section" aria-labelledby="prediction-title"><div className="amazon-section-heading"><p className="mono">Client-side prediction demo</p><h3 id="prediction-title">Run the exported text model locally.</h3><p>The control uses the compact TF-IDF Logistic Regression artifact, not the best SVM, because its coefficients can be represented in static JSON. It uses text only; category, price, and discount are not inference features.</p></div><div className="amazon-predict-grid"><label><span className="mono">Product or review text</span><textarea value={predictionInput} onChange={(event) => { setPredictionInput(event.target.value); setPrediction(null); }} placeholder="Describe a product experience in English…" rows={5} /><button type="button" className="reset-button mono" onClick={() => setPrediction(runInference(predictionInput, model.inference))}>Estimate high-rating likelihood</button></label><div className="amazon-prediction-output" aria-live="polite">{!prediction && <p className="playground-note">No text has been scored. The exported vocabulary has {compact.format(Object.keys(model.inference.vocabulary).length)} terms and n-grams.</p>}{prediction && "error" in prediction && <p className="playground-note">{prediction.error}</p>}{prediction && !("error" in prediction) && <><p className="mono">Estimated likelihood / rating ≥ {evaluation.threshold}</p><strong>{percent(prediction.probability)}</strong><p>{prediction.probability >= 0.5 ? "The text falls on the higher-likelihood side of this exported model’s 0.5 probability cut-off." : "The text falls on the not-high side of this exported model’s 0.5 probability cut-off."}</p><div className="amazon-match-list">{prediction.matches.map((match) => <span key={match.term}>{match.term}<i>{match.contribution >= 0 ? "+" : ""}{match.contribution.toFixed(3)}</i></span>)}</div></>}</div></div><p className="playground-note">This illustrative local inference is limited to the supplied snapshot and should not be used to rank, sell, or make decisions about products.</p></section>
    <section id="method" className="amazon-method-note"><p className="mono">Method and data limits</p><div><p>Numeric price, discount, rating, and rating-count strings are normalized; exact duplicates are removed; and missing rating values are retained rather than imputed. The high-rating target is rating ≥ {evaluation.threshold}.</p><p>There are {quality.missingByField.rating} missing ratings and {quality.missingByField.rating_count} missing rating-count values. This is a single catalog/review snapshot: it contains no sales, conversion, time-series, experimental, or causal labels.</p></div></section>
  </div>;
}
