"use client";

import { useMemo, useState } from "react";

export type PlaygroundRow = { month: string; category: string; value: number; volume: number };
type SortKey = "value" | "volume";

export function DataPlayground({ data }: { data: PlaygroundRow[] }) {
  const [category, setCategory] = useState("All");
  const [sortBy, setSortBy] = useState<SortKey>("value");
  if (!data.length) return <section id="playground" className="section playground-section" aria-labelledby="playground-title"><div className="page-width"><p className="section-label mono">05 / Data playground</p><h2 id="playground-title" className="section-title">A small system to inspect.</h2><div className="empty-state" role="status"><p className="mono">No local demo data available</p><p>Add records to <code>content/data/playground.json</code>, then rebuild the static site.</p></div></div></section>;
  const categories = ["All", ...Array.from(new Set(data.map((row) => row.category)))];
  const filtered = useMemo(() => data.filter((row) => category === "All" || row.category === category), [category, data]);
  const ordered = useMemo(() => [...filtered].sort((left, right) => right[sortBy] - left[sortBy]), [filtered, sortBy]);
  const totalValue = filtered.reduce((sum, row) => sum + row.value, 0);
  const totalVolume = filtered.reduce((sum, row) => sum + row.volume, 0);
  const max = Math.max(...filtered.map((row) => row.value), 1);
  const points = filtered.map((row, index) => `${30 + index * (320 / Math.max(filtered.length - 1, 1))},${164 - (row.value / max) * 124}`).join(" ");

  return <section id="playground" className="section playground-section" aria-labelledby="playground-title"><div className="page-width"><p className="section-label mono">05 / Data playground</p><div className="playground-heading"><h2 id="playground-title" className="section-title">A small system to inspect.</h2><p className="body-copy">Synthetic demo data only. Filter a lightweight local dataset to inspect the relationship between a modeled value and operational volume.</p></div><div className="playground-controls"><div className="filter-list" aria-label="Filter local demo data">{categories.map((item) => <button type="button" aria-pressed={category === item} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div><button className="reset-button mono" type="button" onClick={() => { setCategory("All"); setSortBy("value"); }}>Reset</button></div><div className="kpi-grid" aria-live="polite"><div><span className="mono">Value index</span><strong>{totalValue}</strong><p>Summed within the active view.</p></div><div><span className="mono">Operational volume</span><strong>{totalVolume}</strong><p>Local synthetic record total.</p></div><div><span className="mono">Active series</span><strong>{filtered.length}</strong><p>Rows visible in the chart.</p></div></div><div className="playground-grid"><div className="chart-panel"><div className="chart-heading"><p className="mono">Value by sequence</p><span>Local / synthetic</span></div><svg viewBox="0 0 380 190" role="img" aria-label="Line chart showing the active synthetic value index"><path d="M30 164H350M30 102H350M30 40H350" /><polyline points={points} /><g>{filtered.map((row, index) => <circle key={`${row.month}-${row.category}`} cx={30 + index * (320 / Math.max(filtered.length - 1, 1))} cy={164 - (row.value / max) * 124} r="4"><title>{`${row.month}: ${row.value}`}</title></circle>)}</g></svg><div className="chart-axis">{filtered.map((row) => <span key={`${row.month}-${row.category}`}>{row.month}</span>)}</div></div><div className="table-panel"><div className="table-heading"><p className="mono">Rows</p><div><button type="button" aria-pressed={sortBy === "value"} onClick={() => setSortBy("value")}>Value</button><button type="button" aria-pressed={sortBy === "volume"} onClick={() => setSortBy("volume")}>Volume</button></div></div><div className="table-scroll"><table aria-label="Active synthetic data rows"><thead><tr><th scope="col">Month</th><th scope="col">Category</th><th scope="col">Value</th><th scope="col">Volume</th></tr></thead><tbody>{ordered.map((row) => <tr key={`${row.month}-${row.category}`}><td>{row.month}</td><td>{row.category}</td><td>{row.value}</td><td>{row.volume}</td></tr>)}</tbody></table></div></div></div><p className="playground-note">This playground is intentionally synthetic and illustrative. It demonstrates an inspectable client-side interaction pattern, not a business claim.</p></div></section>;
}
