import json
import os

# Complete Brazil 27 States with exact data from geografis_analysis.md and Brazilian geographic standards
states_data = [
    {
        "uf": "SP",
        "name": "São Paulo",
        "region": "Southeast",
        "orders": 40501,
        "revenue": 5770266.20,
        "revenue_pct": 37.4,
        "aov": 142.50,
        "avg_lead_time": 7.8,
        "avg_distance": 185.4,
        "seller_count": 1849,
        "top_city": "São Paulo (R$ 2.11M)",
        "cross_state_pct": 21.4,
        "x": 620, "y": 680, # SVG Map coordinate anchor
        "insight": "Largest market generating 37.4% of national GMV. Home to 59.7% of all active sellers."
    },
    {
        "uf": "RJ",
        "name": "Rio de Janeiro",
        "region": "Southeast",
        "orders": 12350,
        "revenue": 2055690.40,
        "revenue_pct": 13.3,
        "aov": 166.40,
        "avg_lead_time": 14.2,
        "avg_distance": 430.2,
        "seller_count": 171,
        "top_city": "Rio de Janeiro (R$ 1.11M)",
        "cross_state_pct": 74.8,
        "x": 710, "y": 670,
        "insight": "#2 market nationally. Prime candidate for secondary regional cross-docking fulfillment hub."
    },
    {
        "uf": "MG",
        "name": "Minas Gerais",
        "region": "Southeast",
        "orders": 11354,
        "revenue": 1819277.60,
        "revenue_pct": 11.8,
        "aov": 160.20,
        "avg_lead_time": 11.9,
        "avg_distance": 510.8,
        "seller_count": 244,
        "top_city": "Belo Horizonte (R$ 406k)",
        "cross_state_pct": 68.2,
        "x": 670, "y": 600,
        "insight": "#3 market nationally. Strategic transit nexus connecting Southeast and Northeast corridors."
    },
    {
        "uf": "RS",
        "name": "Rio Grande do Sul",
        "region": "South",
        "orders": 5345,
        "revenue": 861802.40,
        "revenue_pct": 5.6,
        "aov": 161.20,
        "avg_lead_time": 14.8,
        "avg_distance": 890.1,
        "seller_count": 129,
        "top_city": "Porto Alegre (R$ 214k)",
        "cross_state_pct": 82.1,
        "x": 550, "y": 830,
        "insight": "Southern economic leader with high purchasing power but heavy cross-state transit dependency."
    },
    {
        "uf": "PR",
        "name": "Paraná",
        "region": "South",
        "orders": 4923,
        "revenue": 781919.60,
        "revenue_pct": 5.1,
        "aov": 158.80,
        "avg_lead_time": 11.6,
        "avg_distance": 620.5,
        "seller_count": 183,
        "top_city": "Curitiba (R$ 238k)",
        "cross_state_pct": 71.5,
        "x": 560, "y": 720,
        "insight": "Strong agricultural and industrial consumer base with moderate delivery lead times."
    },
    {
        "uf": "SC",
        "name": "Santa Catarina",
        "region": "South",
        "orders": 3546,
        "revenue": 595208.40,
        "revenue_pct": 3.9,
        "aov": 167.80,
        "avg_lead_time": 13.9,
        "avg_distance": 740.0,
        "seller_count": 190,
        "top_city": "Florianópolis (R$ 112k)",
        "cross_state_pct": 77.4,
        "x": 580, "y": 770,
        "insight": "High seller concentration relative to population; well-integrated southern distribution."
    },
    {
        "uf": "BA",
        "name": "Bahia",
        "region": "Northeast",
        "orders": 3256,
        "revenue": 591270.60,
        "revenue_pct": 3.8,
        "aov": 181.60,
        "avg_lead_time": 15.6,
        "avg_distance": 1350.2,
        "seller_count": 19,
        "top_city": "Salvador (R$ 207k)",
        "cross_state_pct": 94.2,
        "x": 760, "y": 480,
        "insight": "Largest northeastern consumer market. High freight distances due to lack of local seller base."
    },
    {
        "uf": "DF",
        "name": "Distrito Federal",
        "region": "Central-West",
        "orders": 2080,
        "revenue": 346146.20,
        "revenue_pct": 2.2,
        "aov": 166.40,
        "avg_lead_time": 12.3,
        "avg_distance": 870.0,
        "seller_count": 30,
        "top_city": "Brasília (R$ 345k)",
        "cross_state_pct": 91.0,
        "x": 590, "y": 510,
        "insight": "Federal capital hub with affluent civil servant base and high online purchasing frequency."
    },
    {
        "uf": "GO",
        "name": "Goiás",
        "region": "Central-West",
        "orders": 1957,
        "revenue": 334294.20,
        "revenue_pct": 2.2,
        "aov": 170.80,
        "avg_lead_time": 14.7,
        "avg_distance": 820.4,
        "seller_count": 40,
        "top_city": "Goiânia (R$ 130k)",
        "cross_state_pct": 89.5,
        "x": 550, "y": 530,
        "insight": "Key agribusiness hub with expanding e-commerce demand and stable order value."
    },
    {
        "uf": "ES",
        "name": "Espírito Santo",
        "region": "Southeast",
        "orders": 1995,
        "revenue": 317682.60,
        "revenue_pct": 2.1,
        "aov": 159.20,
        "avg_lead_time": 15.1,
        "avg_distance": 780.6,
        "seller_count": 23,
        "top_city": "Vitória (R$ 78k)",
        "cross_state_pct": 88.0,
        "x": 760, "y": 620,
        "insight": "Coastal southeast state benefiting from proximity to RJ and SP logistics hubs."
    },
    {
        "uf": "PE",
        "name": "Pernambuco",
        "region": "Northeast",
        "orders": 1593,
        "revenue": 313904.50,
        "revenue_pct": 2.0,
        "aov": 197.00,
        "avg_lead_time": 17.5,
        "avg_distance": 2100.0,
        "seller_count": 9,
        "top_city": "Recife (R$ 128k)",
        "cross_state_pct": 96.5,
        "x": 860, "y": 380,
        "insight": "Northeastern tech and trade hub with higher average basket size balancing longer shipping."
    },
    {
        "uf": "CE",
        "name": "Ceará",
        "region": "Northeast",
        "orders": 1308,
        "revenue": 272464.30,
        "revenue_pct": 1.8,
        "aov": 208.30,
        "avg_lead_time": 20.3,
        "avg_distance": 2350.0,
        "seller_count": 13,
        "top_city": "Fortaleza (R$ 134k)",
        "cross_state_pct": 97.2,
        "x": 800, "y": 300,
        "insight": "Long-distance coastal market experiencing ~20-day delivery cycles from São Paulo."
    },
    {
        "uf": "PA",
        "name": "Pará",
        "region": "North",
        "orders": 947,
        "revenue": 212543.80,
        "revenue_pct": 1.4,
        "aov": 224.40,
        "avg_lead_time": 22.8,
        "avg_distance": 2480.0,
        "seller_count": 1,
        "top_city": "Belém (R$ 102k)",
        "cross_state_pct": 99.8,
        "x": 520, "y": 280,
        "insight": "Amazonian gateway with high freight barrier driving basket consolidation >R$ 220."
    },
    {
        "uf": "MT",
        "name": "Mato Grosso",
        "region": "Central-West",
        "orders": 886,
        "revenue": 182746.50,
        "revenue_pct": 1.2,
        "aov": 206.20,
        "avg_lead_time": 17.6,
        "avg_distance": 1420.0,
        "seller_count": 4,
        "top_city": "Cuiabá (R$ 84k)",
        "cross_state_pct": 98.4,
        "x": 420, "y": 500,
        "insight": "High-income agribusiness region with above-average basket sizes."
    },
    {
        "uf": "MA",
        "name": "Maranhão",
        "region": "Northeast",
        "orders": 717,
        "revenue": 154687.20,
        "revenue_pct": 1.0,
        "aov": 215.70,
        "avg_lead_time": 20.8,
        "avg_distance": 2280.0,
        "seller_count": 1,
        "top_city": "São Luís (R$ 72k)",
        "cross_state_pct": 99.5,
        "x": 680, "y": 300,
        "insight": "Challenging northern logistics corridor requiring ~21 days transit from southeast warehouses."
    },
    {
        "uf": "MS",
        "name": "Mato Grosso do Sul",
        "region": "Central-West",
        "orders": 699,
        "revenue": 133596.10,
        "revenue_pct": 0.9,
        "aov": 191.10,
        "avg_lead_time": 14.9,
        "avg_distance": 890.0,
        "seller_count": 5,
        "top_city": "Campo Grande (R$ 68k)",
        "cross_state_pct": 96.0,
        "x": 460, "y": 620,
        "insight": "Southern central-west state with steady consumer purchasing power."
    },
    {
        "uf": "PB",
        "name": "Paraíba",
        "region": "Northeast",
        "orders": 517,
        "revenue": 136274.60,
        "revenue_pct": 0.9,
        "aov": 263.50,
        "avg_lead_time": 19.8,
        "avg_distance": 2210.0,
        "seller_count": 6,
        "top_city": "João Pessoa (R$ 64k)",
        "cross_state_pct": 97.5,
        "x": 870, "y": 340,
        "insight": "Highest AOV in the Northeast region (>R$ 260) with strong premium consumer demand."
    },
    {
        "uf": "PI",
        "name": "Piauí",
        "region": "Northeast",
        "orders": 482,
        "revenue": 105847.40,
        "revenue_pct": 0.7,
        "aov": 219.60,
        "avg_lead_time": 18.9,
        "avg_distance": 2080.0,
        "seller_count": 1,
        "top_city": "Teresina (R$ 56k)",
        "cross_state_pct": 99.2,
        "x": 720, "y": 360,
        "insight": "High dependency on national distribution; minimal local seller coverage."
    },
    {
        "uf": "RN",
        "name": "Rio Grande do Norte",
        "region": "Northeast",
        "orders": 474,
        "revenue": 108745.20,
        "revenue_pct": 0.7,
        "aov": 229.40,
        "avg_lead_time": 18.6,
        "avg_distance": 2310.0,
        "seller_count": 2,
        "top_city": "Natal (R$ 59k)",
        "cross_state_pct": 98.7,
        "x": 860, "y": 320,
        "insight": "Coastal tourist economy with concentrated urban delivery demand in Natal."
    },
    {
        "uf": "AL",
        "name": "Alagoas",
        "region": "Northeast",
        "orders": 401,
        "revenue": 92350.80,
        "revenue_pct": 0.6,
        "aov": 230.30,
        "avg_lead_time": 23.5,
        "avg_distance": 1920.0,
        "seller_count": 1,
        "top_city": "Maceió (R$ 51k)",
        "cross_state_pct": 99.0,
        "x": 850, "y": 420,
        "insight": "High transit duration (~23.5 days) creating customer friction and review score pressure."
    },
    {
        "uf": "SE",
        "name": "Sergipe",
        "region": "Northeast",
        "orders": 341,
        "revenue": 72154.20,
        "revenue_pct": 0.5,
        "aov": 211.60,
        "avg_lead_time": 20.4,
        "avg_distance": 1780.0,
        "seller_count": 2,
        "top_city": "Aracaju (R$ 44k)",
        "cross_state_pct": 98.2,
        "x": 830, "y": 440,
        "insight": "Smallest geographical state in Brazil with high urban concentration in Aracaju."
    },
    {
        "uf": "TO",
        "name": "Tocantins",
        "region": "North",
        "orders": 274,
        "revenue": 60578.40,
        "revenue_pct": 0.4,
        "aov": 221.10,
        "avg_lead_time": 16.8,
        "avg_distance": 1490.0,
        "seller_count": 0,
        "top_city": "Palmas (R$ 29k)",
        "cross_state_pct": 100.0,
        "x": 600, "y": 400,
        "insight": "100% cross-state reliance. Fast-growing agricultural state with zero local seller base."
    },
    {
        "uf": "RO",
        "name": "Rondônia",
        "region": "North",
        "orders": 243,
        "revenue": 56975.70,
        "revenue_pct": 0.4,
        "aov": 234.50,
        "avg_lead_time": 19.3,
        "avg_distance": 2420.0,
        "seller_count": 2,
        "top_city": "Porto Velho (R$ 31k)",
        "cross_state_pct": 98.8,
        "x": 310, "y": 450,
        "insight": "Western Amazonian state with high basket value (R$ 234.50) offsetting high freight costs."
    },
    {
        "uf": "AM",
        "name": "Amazonas",
        "region": "North",
        "orders": 145,
        "revenue": 27596.20,
        "revenue_pct": 0.2,
        "aov": 190.30,
        "avg_lead_time": 25.6,
        "avg_distance": 2690.0,
        "seller_count": 1,
        "top_city": "Manaus (R$ 22k)",
        "cross_state_pct": 98.6,
        "x": 260, "y": 280,
        "insight": "Longest average delivery lead time (25.6 days) due to river-based transit routes."
    },
    {
        "uf": "AC",
        "name": "Acre",
        "region": "North",
        "orders": 80,
        "revenue": 19586.20,
        "revenue_pct": 0.1,
        "aov": 244.80,
        "avg_lead_time": 20.4,
        "avg_distance": 2780.0,
        "seller_count": 0,
        "top_city": "Rio Branco (R$ 15k)",
        "cross_state_pct": 100.0,
        "x": 160, "y": 440,
        "insight": "Farthest western state (>2,700 km). Second highest AOV nationally (R$ 244.80)."
    },
    {
        "uf": "AP",
        "name": "Amapá",
        "region": "North",
        "orders": 67,
        "revenue": 16141.80,
        "revenue_pct": 0.1,
        "aov": 240.90,
        "avg_lead_time": 26.2,
        "avg_distance": 2650.0,
        "seller_count": 0,
        "top_city": "Macapá (R$ 13k)",
        "cross_state_pct": 100.0,
        "x": 510, "y": 160,
        "insight": "Isolated northern delta state with 26.2 days lead time and 100% reliance on out-of-state fulfillment."
    },
    {
        "uf": "RR",
        "name": "Roraima",
        "region": "North",
        "orders": 41,
        "revenue": 9039.50,
        "revenue_pct": 0.1,
        "aov": 220.50,
        "avg_lead_time": 27.9,
        "avg_distance": 3280.0,
        "seller_count": 0,
        "top_city": "Boa Vista (R$ 8k)",
        "cross_state_pct": 100.0,
        "x": 300, "y": 140,
        "insight": "Farthest northern state (3,280 km). Longest transit time nationally (27.9 days)."
    }
]

# Distance Buckets data from geografis_analysis.md
distance_buckets = [
    {
        "bucket": "0 – 50 km (Metro/Local)",
        "orders": 11729,
        "lead_time": 5.70,
        "buffer_days": -9.45,
        "transit_speed": "Fastest (~5.7d)",
        "logistics_type": "Same-City / Metro Courier"
    },
    {
        "bucket": "50 – 200 km (Intra-State)",
        "orders": 12892,
        "lead_time": 7.55,
        "buffer_days": -10.46,
        "transit_speed": "Standard Local (~7.5d)",
        "logistics_type": "Regional Hub Direct Dispatch"
    },
    {
        "bucket": "200 – 500 km (Regional)",
        "orders": 30255,
        "lead_time": 11.66,
        "buffer_days": -12.28,
        "transit_speed": "Moderate (~11.7d)",
        "logistics_type": "Inter-City Road Transit"
    },
    {
        "bucket": "500 – 1,000 km (Inter-State)",
        "orders": 25744,
        "lead_time": 13.84,
        "buffer_days": -12.70,
        "transit_speed": "Slow (~13.8d)",
        "logistics_type": "Long-Haul Corridor Trunking"
    },
    {
        "bucket": "1,000 – 2,000 km (Long-Haul)",
        "orders": 9744,
        "lead_time": 17.51,
        "buffer_days": -12.84,
        "transit_speed": "Very Slow (~17.5d)",
        "logistics_type": "Multi-Hub Transshipment"
    },
    {
        "bucket": "> 2,000 km (Cross-Continental)",
        "orders": 5610,
        "lead_time": 20.71,
        "buffer_days": -12.68,
        "transit_speed": "Extreme (~20.7d)",
        "logistics_type": "Remote / Air Freight / River"
    }
]

# 9-Tier RFM Customer Segments data from rfm_analysis.md
rfm_segments = [
    {
        "segment": "Cannot Lose Them",
        "customers": 13757,
        "customers_pct": 14.7,
        "avg_recency": 443.1,
        "avg_frequency": 1.0,
        "avg_monetary": 307.90,
        "total_revenue": 4235679.20,
        "revenue_pct": 27.5,
        "status": "Critical Churn Risk",
        "recommended_action": "Aggressive high-value win-back campaigns: large reactivation vouchers & personalized retention outreach."
    },
    {
        "segment": "Promising Big Spender",
        "customers": 14170,
        "customers_pct": 15.2,
        "avg_recency": 226.3,
        "avg_frequency": 1.0,
        "avg_monetary": 291.70,
        "total_revenue": 4133200.90,
        "revenue_pct": 26.8,
        "status": "High Opportunity",
        "recommended_action": "Targeted cross-sell reminders and category-specific retargeting before entering dormant status."
    },
    {
        "segment": "New High-Value",
        "customers": 7178,
        "customers_pct": 7.7,
        "avg_recency": 95.7,
        "avg_frequency": 1.0,
        "avg_monetary": 301.00,
        "total_revenue": 2160665.70,
        "revenue_pct": 14.0,
        "status": "Prime Champion Conversion",
        "recommended_action": "Rapid post-delivery follow-up offering 2nd-order incentives within 30–60 days to build repeat habits."
    },
    {
        "segment": "Hibernating Low-Value",
        "customers": 22519,
        "customers_pct": 24.1,
        "avg_recency": 445.1,
        "avg_frequency": 1.0,
        "avg_monetary": 72.70,
        "total_revenue": 1636999.40,
        "revenue_pct": 10.6,
        "status": "Low ROI Cohort",
        "recommended_action": "Low-cost mass automated email newsletters; avoid expensive ad spend or heavy voucher subsidies."
    },
    {
        "segment": "Promising Mid-Tier",
        "customers": 22029,
        "customers_pct": 23.6,
        "avg_recency": 227.5,
        "avg_frequency": 1.0,
        "avg_monetary": 72.60,
        "total_revenue": 1598833.70,
        "revenue_pct": 10.4,
        "status": "Warm Prospects",
        "recommended_action": "Nurture sequence with tiered cart discounts to drive basket expansion on subsequent orders."
    },
    {
        "segment": "New General Customers",
        "customers": 10904,
        "customers_pct": 11.7,
        "avg_recency": 93.9,
        "avg_frequency": 1.0,
        "avg_monetary": 72.70,
        "total_revenue": 792725.60,
        "revenue_pct": 5.1,
        "status": "Fresh Buyers",
        "recommended_action": "Welcome sequence with curated product recommendations and loyalty point activation."
    },
    {
        "segment": "Champions (True Loyal)",
        "customers": 1208,
        "customers_pct": 1.3,
        "avg_recency": 138.3,
        "avg_frequency": 2.2,
        "avg_monetary": 322.40,
        "total_revenue": 389436.50,
        "revenue_pct": 2.5,
        "status": "Top Tier VIP",
        "recommended_action": "Exclusive VIP perks, early product drops, priority customer support, and ambassador rewards."
    },
    {
        "segment": "At Risk (Repeat Churn)",
        "customers": 993,
        "customers_pct": 1.1,
        "avg_recency": 430.9,
        "avg_frequency": 2.1,
        "avg_monetary": 292.70,
        "total_revenue": 290663.30,
        "revenue_pct": 1.9,
        "status": "Fading Loyals",
        "recommended_action": "Satisfaction survey + personalized re-activation deals tailored to their past repeat purchase categories."
    },
    {
        "segment": "Loyal Customers",
        "customers": 600,
        "customers_pct": 0.6,
        "avg_recency": 266.4,
        "avg_frequency": 2.1,
        "avg_monetary": 307.10,
        "total_revenue": 184257.40,
        "revenue_pct": 1.2,
        "status": "Established Loyals",
        "recommended_action": "Quarterly loyalty appreciation gifts and subscription-based automatic replenishment offers."
    }
]

output_payload = {
    "metadata": {
        "title": "Olist Brazilian E-Commerce Supply Chain & Customer Intelligence",
        "source": "Olist E-Commerce Dataset (Kaggle) 2016-2018",
        "total_gmv": 16008872.12,
        "total_orders": 99441,
        "unique_customers": 96096,
        "delivered_customers": 93358,
        "states_count": 27,
        "seller_count": 3095
    },
    "states": states_data,
    "distance_buckets": distance_buckets,
    "rfm_segments": rfm_segments
}

out_path = r"C:\Users\HYPE AMD\Documents\FILE\PROJECT\PORTOFOLIO\01. Vercel\project\content\data\olist_analysis.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(output_payload, f, indent=2)

print(f"Successfully generated {out_path} with {len(states_data)} states, {len(distance_buckets)} distance buckets, and {len(rfm_segments)} RFM segments.")
